Update Setup

diff --git a/Setup b/Setup
--- a/Setup
+++ b/Setup
@@ -6,7 +6,7 @@ USERNAME=kali
 
 function unsupported_arch() {
     printf "${red}"
-    echo "[*] Arquitetura não suportada\n\n"
+    echo "[*] Unsupported Architecture\n\n"
     printf "${reset}"
     exit
 }
@@ -46,7 +46,7 @@ function ask() {
 }
 
 function get_arch() {
-    printf "${blue}[*] Verificando a arquitetura do dispositivo ..."
+    printf "${blue}[*] Checking device architecture ..."
     case $(getprop ro.product.cpu.abi) in
         arm64-v8a)
             SYS_ARCH=arm64
@@ -69,7 +69,7 @@ function set_strings() {
 function prepare_fs() {
     unset KEEP_CHROOT
     if [ -d ${CHROOT} ]; then
-        if ask "Diretório rootfs existente encontrado. Excluir e criar um novo?" "N"; then
+        if ask "Existing rootfs directory found. Delete and create a new one?" "N"; then
             rm -rf ${CHROOT}
         else
             KEEP_CHROOT=1
@@ -79,7 +79,7 @@ function prepare_fs() {
 
 function cleanup() {
     if [ -f ${IMAGE_NAME} ]; then
-        if ask "Excluir arquivo rootfs baixado?" "N"; then
+        if ask "Delete downloaded rootfs file?" "N"; then
 	    if [ -f ${IMAGE_NAME} ]; then
                 rm -f ${IMAGE_NAME}
 	    fi
@@ -91,7 +91,7 @@ function cleanup() {
 } 
 
 function check_dependencies() {
-    printf "${blue}\n[*] Verificando as dependências do pacotes...${reset}\n"
+    printf "${blue}\n[*] Checking package dependencies...${reset}\n"
     ## Workaround for termux-app issue #1283 (https://github.com/termux/termux-app/issues/1283)
     ##apt update -y &> /dev/null
     apt-get update -y &> /dev/null || apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" dist-upgrade -y &> /dev/null
@@ -102,7 +102,7 @@ function check_dependencies() {
         else
             printf "Installing ${i}...\n"
             apt install -y $i || {
-                printf "${red}ERROR: Falha ao instalar pacotes.\n Exiting.\n${reset}"
+                printf "${red}ERROR: Failed to install packages.\n Exiting.\n${reset}"
 	        exit
             }
         fi
@@ -119,15 +119,15 @@ function get_url() {
 function get_rootfs() {
     unset KEEP_IMAGE
     if [ -f ${IMAGE_NAME} ]; then
-        if ask "Arquivo de imagem existente encontrado. Excluir e baixar um novo?" "N"; then
+        if ask "Existing image file found. Delete and download a new one?" "N"; then
             rm -f ${IMAGE_NAME}
         else
-            printf "${yellow}[!] Usando o arquivo rootfs existente${reset}\n"
+            printf "${yellow}[!] Using existing rootfs archive${reset}\n"
             KEEP_IMAGE=1
             return
         fi
     fi
-    printf "${blue}[*] Baixando rootfs...${reset}\n\n"
+    printf "${blue}[*] Downloading rootfs...${reset}\n\n"
     get_url
     wget ${EXTRA_ARGS} --continue "${ROOTFS_URL}"
 }
@@ -145,9 +145,9 @@ function get_sha() {
 
 function verify_sha() {
     if [ -z $KEEP_IMAGE ]; then
-        printf "\n${blue}[*] Verificando a integridade do rootfs...${reset}\n\n"
+        printf "\n${blue}[*] Verifying integrity of rootfs...${reset}\n\n"
         sha512sum -c $SHA_NAME || {
-            printf "${red} Rootfs corrompido. Execute este instalador novamente ou baixe o arquivo manualmente\n${reset}"
+            printf "${red} Rootfs corrupted. Please run this installer again or download the file manually\n${reset}"
             exit 1
         }
     fi
@@ -155,18 +155,18 @@ function verify_sha() {
 
 function extract_rootfs() {
     if [ -z $KEEP_CHROOT ]; then
-        printf "\n${blue}[*] Extraindo rootfs... ${reset}\n\n"
+        printf "\n${blue}[*] Extracting rootfs... ${reset}\n\n"
         proot --link2symlink tar -xf $IMAGE_NAME 2> /dev/null || :
     else        
-        printf "${yellow}[!]Usando o diretório rootfs existente${reset}\n"
+        printf "${yellow}[!] Using existing rootfs directory${reset}\n"
     fi
 }
 
 
 function create_launcher() {
-    KALI_LAUNCHER=${PREFIX}/bin/KALI
-    KALI_SHORTCUT=${PREFIX}/bin/KALI
-    cat > $KALI_LAUNCHER <<- EOF
+    NH_LAUNCHER=${PREFIX}/bin/nethunter
+    NH_SHORTCUT=${PREFIX}/bin/nh
+    cat > $NH_LAUNCHER <<- EOF
 #!/data/data/com.termux/files/usr/bin/bash -e
 cd \${HOME}
 ## termux-exec sets LD_PRELOAD so let's unset it before continuing
@@ -181,7 +181,7 @@ user="$USERNAME"
 home="/home/\$user"
 start="sudo -u kali /bin/bash"
 
-## KALI can be launched as root with the "-r" cmd attribute
+## NH can be launched as root with the "-r" cmd attribute
 ## Also check if user kali exists, if not start as root
 if grep -q "kali" ${CHROOT}/etc/passwd; then
     KALIUSR="1";
@@ -220,12 +220,12 @@ else
 fi
 EOF
 
-    chmod 700 $KALI_LAUNCHER
-    if [ -L ${KALI_SHORTCUT} ]; then
-        rm -f ${KALI_SHORTCUT}
+    chmod 700 $NH_LAUNCHER
+    if [ -L ${NH_SHORTCUT} ]; then
+        rm -f ${NH_SHORTCUT}
     fi
-    if [ ! -f ${KALI_SHORTCUT} ]; then
-        ln -s ${KALI_LAUNCHER} ${KALI_SHORTCUT} >/dev/null
+    if [ ! -f ${NH_SHORTCUT} ]; then
+        ln -s ${NH_LAUNCHER} ${NH_SHORTCUT} >/dev/null
     fi
    
 }
@@ -235,6 +235,73 @@ function create_kex_launcher() {
     cat > $KEX_LAUNCHER <<- EOF
 #!/bin/bash
 
+function start-kex() {
+    if [ ! -f ~/.vnc/passwd ]; then
+        passwd-kex
+    fi
+    USR=\$(whoami)
+    if [ \$USR == "root" ]; then
+        SCREEN=":2"
+    else
+        SCREEN=":1"
+    fi 
+    export HOME=\${HOME}; export USER=\${USR}; LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgcc_s.so.1 nohup vncserver \$SCREEN >/dev/null 2>&1 </dev/null
+    starting_kex=1
+    return 0
+}
+
+function stop-kex() {
+    vncserver -kill :1 | sed s/"Xtigervnc"/"NetHunter KeX"/
+    vncserver -kill :2 | sed s/"Xtigervnc"/"NetHunter KeX"/
+    return $?
+}
+
+function passwd-kex() {
+    vncpasswd
+    return $?
+}
+
+function status-kex() {
+    sessions=\$(vncserver -list | sed s/"TigerVNC"/"NetHunter KeX"/)
+    if [[ \$sessions == *"590"* ]]; then
+        printf "\n\${sessions}\n"
+        printf "\nYou can use the KeX client to connect to any of these displays.\n\n"
+    else
+        if [ ! -z \$starting_kex ]; then
+            printf '\nError starting the KeX server.\nPlease try "nethunter kex kill" or restart your termux session and try again.\n\n'
+        fi
+    fi
+    return 0
+}
+
+function kill-kex() {
+    pkill Xtigervnc
+    return \$?
+}
+
+case \$1 in
+    start)
+        start-kex
+        ;;
+    stop)
+        stop-kex
+        ;;
+    status)
+        status-kex
+        ;;
+    passwd)
+        passwd-kex
+        ;;
+    kill)
+        kill-kex
+        ;;
+    *)
+        stop-kex
+        start-kex
+        status-kex
+        ;;
+esac
+EOF
 
     chmod 700 $KEX_LAUNCHER
 }
@@ -260,24 +327,24 @@ function fix_uid() {
     ## Change kali uid and gid to match that of the termux user
     USRID=$(id -u)
     GRPID=$(id -g)
-    KALI -r usermod -u $USRID kali 2>/dev/null
-    KALI -r groupmod -g $GRPID kali 2>/dev/null
+    nh -r usermod -u $USRID kali 2>/dev/null
+    nh -r groupmod -g $GRPID kali 2>/dev/null
 }
 
 function print_banner() {
     clear
     printf "${blue}##################################################\n"
-    printf "${green}##                                              ##\n"
-    printf "${green}##  88      a8P         db        88        88  ##\n"
-    printf "${green}##  88    .88'         d88b       88        88  ##\n"
-    printf "${green}##  88   88'          d8''8b      88        88  ##\n"
-    printf "${green}##  88 d88           d8'  '8b     88        88  ##\n"
-    printf "${blue}##   8888'88.        d8YaaaaY8b    88        88  ##\n"
-    printf "${yellow}## 88P   Y8b      d8''''''''8b   88        88  ##\n"
-    printf "${yellow}## 88     '88.   d8'        '8b  88        88  ##\n"
-    printf "${yellow}## 88       Y8b d8'          '8b 888888888 88  ##\n"
-    printf "${yellow}##                                              ##\n"
-    printf "${red}################# Gilmar Filho #####################${reset}\n\n"
+    printf "${blue}##                                              ##\n"
+    printf "${blue}##  88      a8P         db        88        88  ##\n"
+    printf "${blue}##  88    .88'         d88b       88        88  ##\n"
+    printf "${blue}##  88   88'          d8''8b      88        88  ##\n"
+    printf "${blue}##  88 d88           d8'  '8b     88        88  ##\n"
+    printf "${blue}##  8888'88.        d8YaaaaY8b    88        88  ##\n"
+    printf "${blue}##  88P   Y8b      d8''''''''8b   88        88  ##\n"
+    printf "${blue}##  88     '88.   d8'        '8b  88        88  ##\n"
+    printf "${blue}##  88       Y8b d8'          '8b 888888888 88  ##\n"
+    printf "${blue}##                                              ##\n"
+    printf "${blue}####  ############# NetHunter ####################${reset}\n\n"
 }
 
 
@@ -313,13 +380,60 @@ extract_rootfs
 create_launcher
 cleanup
 
-printf "\n${blue}[*] Configurando Kali no Termux ...\n"
+printf "\n${blue}[*] Configuring NetHunter for Termux ...\n"
 fix_profile_bash
 fix_sudo
 create_kex_launcher
 fix_uid
 
+function print_banner() {
+    clear
+    printf "${blue}##################################################\n"
+    printf "${green}##                                              ##\n"
+    printf "${green}##  88      a8P         db        88        88  ##\n"
+    printf "${green}##  88    .88'         d88b       88        88  ##\n"
+    printf "${green}##  88   88'          d8''8b      88        88  ##\n"
+    printf "${green}##  88 d88           d8'  '8b     88        88  ##\n"
+    printf "${blue}##   8888'88.        d8YaaaaY8b    88        88  ##\n"
+    printf "${yellow}## 88P   Y8b      d8''''''''8b   88        88  ##\n"
+    printf "${yellow}## 88     '88.   d8'        '8b  88        88  ##\n"
+    printf "${yellow}## 88       Y8b d8'          '8b 888888888 88  ##\n"
+    printf "${yellow}##                                              ##\n"
+    printf "${red}################# Gilmar Filho #####################${reset}\n\n"
+}
+##################################
+##              Main            ##
+# Add some colours
+red='\033[1;31m'
+green='\033[1;32m'
+yellow='\033[1;33m'
+blue='\033[1;34m'
+light_cyan='\033[1;96m'
+reset='\033[0m'
+EXTRA_ARGS=""
+if [[ ! -z $1 ]]; then
+    EXTRA_ARGS=$1
+    if [[ $EXTRA_ARGS != "--no-check-certificate" ]]; then
+        EXTRA_ARGS=""
+    fi
+fi
+cd $HOME
+print_banner
+get_arch
+set_strings
+prepare_fs
+check_dependencies
+get_rootfs
+get_sha
+verify_sha
+extract_rootfs
+create_launcher
+cleanup
+printf "\n${blue}[*] Configurando Kali no Termux ...\n"
+fix_profile_bash
+fix_sudo
+create_kex_launcher
+fix_uid
 print_banner
 printf "${green}[=] Kali Linux Instalado com  sucesso${reset}\n\n"
 printf "${green}[+] Iniciar  kali No Termux, type:${reset}\n"
-
